### ISSUE TITLE
Authorize Netlify for this repository (only)

### ISSUE THREAD

**Issue by heuer** [ftCommunity/txpiwebsite#1]
Netlify is used to generate the (static) website.

Since I moved the repository from my account to ftCommunity, Netlify needs access to this repository. I restricted the access rights to this repository, all other repositories within the ftCommunity wouldn't be affected. 

It would be nice if one of the @ftCommunity/owners would authorize the access. I guess you received a request. If not, please contact me.

Thanks in advance.

**Comment by heuer** [comment]
Works, thanks!

**Comment by rkunze** [comment]
Any reason why you don't/can't use [Github pages](https://pages.github.com/)? Especially when the website repo is hosted on Github anyway...

**Comment by heuer** [comment]
I wanted to use GH pages but according to my understanding GH does not support "true" redirects. You can use redirects if you install a Jekyll plugin which generates a HTML page with a HTTP refresh meta tag, though.

But it is not possible to create a redirect from <https://tx-pi.de/tx-pi-setup.sh> to <https://raw.githubusercontent.com/ftCommunity/tx-pi/master/setup/tx-pi-setup.sh> with a status code 302.

We use some 302 redirects (i.e. for downloading the latest images),  so I was looking for a platform which allows custom HTTP status codes.

**Comment by rkunze** [comment]
What is the scenario where you actually need a "real" HTTP redirect and a `<meta http-equiv="refresh">` (or even a simple, old-fashioned link) won't work? 

The only one I can think of would be nice, static URLs for use with command line HTTP clients, but is that really worth bringing in another service?

**Comment by heuer** [comment]
> The only one I can think of would be nice, static URLs for use with command line HTTP clients

Yes, that's our use case.

> but is that really worth bringing in another service?

IMO it does no harm. Do you see any problem? The access is restricted to this repository.
If Netlify is undesirable I can move the repository back to my account and grant access to interested developers. I thought it would be easier to contribute to a repository within the ftCommunity, though.

**Comment by rkunze** [comment]
> Do you see any problem?
No, not really.

It's just one extra dependency (wich means something else that can break), and I usually try to minimize the external dependencies of any project I'm working on. But if you think it's worth it, go ahead.

**Comment by heuer** [comment]
I try to avoid dependencies, too. I think Netlify does no harm. 

Using GH pages adds an additional dependency to GH. 

Let's give Netlify a try.
